DROP DATABASE IF EXISTS TRANSPORTE;
CREATE DATABASE TRANSPORTE;

USE TRANSPORTE;

CREATE TABLE FUNCIONARIO(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100),
    cpf VARCHAR(14),
    turno VARCHAR(20)
);

CREATE TABLE COBRADOR(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY(id) REFERENCES FUNCIONARIO(id)	
);

CREATE TABLE MOTORISTA(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    cnh CHAR(11),
    FOREIGN KEY(id) REFERENCES FUNCIONARIO(id)	
);

CREATE TABLE ONIBUS(
    placa CHAR(7) PRIMARY KEY,
    dataFabr DATE,
    inicioOper DATE
);

CREATE TABLE LINHA(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100)
);

CREATE TABLE VIAGEM(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    dia DATE,
    horario TIME,
    numEntradas INTEGER,
    idCobrador INTEGER,
    idMotorista INTEGER,
    idLinha INTEGER,
    placaOnibus CHAR(7),
    FOREIGN KEY(idCobrador) REFERENCES COBRADOR(id),
    FOREIGN KEY(idMotorista) REFERENCES MOTORISTA(id),	
    FOREIGN KEY(idLinha) REFERENCES LINHA(id),	
    FOREIGN KEY(placaOnibus) REFERENCES ONIBUS(placa)	
);

CREATE TABLE BAIRRO(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100)
);

CREATE TABLE RUA(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100)
);


CREATE TABLE RUA_BAIRRO(
    idRua INTEGER,
    idBairro INTEGER,
    CONSTRAINT pk_rua_bairro PRIMARY KEY(idRua, idBairro),
    FOREIGN KEY(idRua) REFERENCES RUA(id),
    FOREIGN KEY(idBairro) REFERENCES BAIRRO(id)	
);

CREATE TABLE PONTO(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    idRua INTEGER,
    idbairro INTEGER NOT NULL,
    FOREIGN KEY(idRua) REFERENCES RUA(id),	
    FOREIGN KEY(idBairro) REFERENCES BAIRRO(id)	
);

CREATE TABLE VIAGEM_PONTO(
    idViagem INTEGER,
    idPonto INTEGER,
    horario TIME,
    CONSTRAINT pk_viagem_ponto PRIMARY KEY(idViagem, idPonto),
    FOREIGN KEY(idPonto) REFERENCES PONTO(id),
    FOREIGN KEY(idViagem) REFERENCES VIAGEM(id)
);

CREATE TABLE LINHA_PONTO(
    idLinha INTEGER NOT NULL,
    idPonto INTEGER NOT NULL,
    CONSTRAINT pk_linha_ponto PRIMARY KEY(idLinha, idPonto),
    FOREIGN KEY(idLinha) REFERENCES LINHA(id),
    FOREIGN KEY(idPonto) REFERENCES PONTO(id)	
);