/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dao;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import model.Bairro;
//import dao.DBConnection


/**
 *
 * @author alan
 */
public class BairroDao extends javax.swing.JFrame {
    private Connection con;
    private final String sqlInsert = "INSERT INTO RUA(nome) VALUES (?)";
    private final String sqlUpdate = "UPDATE RUA SET nome= ?  WHERE id = ? ";
    private final String sqlRemove = "DELETE FROM RUA WHERE id = ?";
    private final String sqlList   = "SELECT id, nome FROM RUA ORDER BY nome";
    private final String sqlFind   = "SELECT id, nome FROM RUA WHERE id = ?";
    /**
     * Creates new form BairroDao
     */
    public void insert(Bairro bairro) throws SQLException{
        PreparedStatement ps = null;
        try{
            con = connect();
            ps = con.prepareStatement(sqlInsert);
        
            ps.setString(1, bairro.getNome());
            ps.execute();
        }
        finally{
            ps.close();
            close(con);
        }        
    }

    public void update(Bairro bairro) throws SQLException{
        PreparedStatement ps = null;
        try{
            con = connect();
            ps = con.prepareStatement(sqlUpdate);
            ps.setString(1, bairro.getNome());
            ps.setInt(2, bairro.getId());
            ps.execute();
        }
        finally{
            ps.close();
            close(con);
        }
    }
    
    public void remove(int id) throws SQLException{
        PreparedStatement ps = null;
        try{
            con = connect();
            ps = con.prepareStatement(sqlRemove);
            ps.setInt(1, id);
            ps.execute();
        }
        finally{
            ps.close();
            close(con);
        }

    }
    
    public ArrayList<Bairro> list() throws SQLException, ClassNotFoundException, IOException{
        PreparedStatement ps = null;
        ResultSet rs = null;
        try{
            con = connect();
            ps = con.prepareStatement(sqlList);
            rs = ps.executeQuery();
            ArrayList<Bairro> list = new ArrayList<>();
            Bairro bairro;
            while (rs.next()){
                bairro = new Bairro();
                bairro.setId(rs.getInt("id"));
                bairro.setNome(rs.getString("nome"));
                list.add(bairro);
            }
            return list;
        }
        finally{
            rs.close();
            ps.close();
            close(con);
        }
    }
    
    public Bairro find(int id)throws SQLException, ClassNotFoundException, IOException{
        PreparedStatement ps = null;
        ResultSet rs = null;
        try{
            con = connect();
            ps = con.prepareStatement(sqlFind);
            ps.setInt(1, id);

            rs = ps.executeQuery();
            Bairro bairro = null ;
            if (rs.next()){
                bairro = new Bairro();
                bairro.setId(rs.getInt("id"));
                bairro.setNome(rs.getString("nome"));
            }
            return rua;
        }
        finally{
            rs.close();
            ps.close();
            close(con);
        }
        
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BairroDao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BairroDao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BairroDao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BairroDao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BairroDao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
